### ISSUE TITLE
LDAP settings do not show up

### ISSUE THREAD

**Issue by wirepatch** [ink-blot/nodebb-plugin-node-ldap#1]
I've just installed and activated the plugin on top of a »fresh« Nodebb 12 installation. I then restarted nodebb and actually see the »Ldap Settings« title when hitting the »Plugins« tab.

Unfortunately clicking on  »Ldap Settings« reveals nothing but an endlessly spinning wheel to the right of the top Nodebb navigation bar.

So far the only relevant line from the logs say:
```
- /opt/nodebb/app.js)` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at /opt/nodebb/node_modules/nodebb-plugin-node-ldap/index.js:6:40
2020-04-29T21:31:51.273Z [4567/5540] - warn: [authentication] Login override detected, skipping local login strategy.
```
I'd be happy configuring LDAP related parameters manually but having no clue how to do so  I'm stuck.

**Comment by ink-blot** [comment]
Ok. I currently have it running properly with NodeBB 1.13.0 and 1.12.x before that. Not sure what's happening here exactly. I'll have a look.

**Comment by wirepatch** [comment]
Presumably my fault: I read a related topic indicating a »./nodebb rebuild« rather than simply restarting was being required in the context of the nodebb-write-api plugin. I don't know if this relates to the Ldap plugin as well but I'm fine by now.
